name: Flutter CI/CD

on:
  push:
    branches: [ main ] # Substitua pelo nome do seu branch principal

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.2' # Substitua '2.x' pela versão do Flutter que você está usando

    - name: Build Flutter Web
      run: flutter build web

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync build/web/ s3://${{ secrets.S3_BUCKET }} --acl public-read
