name: Flutter CI/CD

on:
  push:
    branches: [ main ] 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.10.2' 

    - name: Build Flutter Web
      run: flutter build web

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --follow-symlinks --delete
        sync_args: --delete
        local_dir: ./build/web/
        s3_bucket: ${{ secrets.S3_BUCKET }} 
        aws-region: ${{ secrets.AWS_REGION }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
